// Todo o texto do site. Para mudar uma frase, editar a entrada em "pt" e em "en".

// Dados comuns às duas línguas.
const SITE = {
  name: "João Gonçalves",
  email: "joaomgoncalves17@gmail.com",
  // TODO: substituir pelos URLs reais.
  linkedin: "https://www.linkedin.com/in/TODO",
  github: "https://github.com/TODO",
  // TODO: colocar a foto em assets/joao.jpg e mudar para "assets/joao.jpg".
  photo: null,
  cv: {
    pt: "assets/cv-joao-goncalves-pt.pdf",
    en: "assets/cv-joao-goncalves-en.pdf",
  },
  googleCertificate: {
    // TODO: colocar a imagem do diploma em assets/google-it-support.png e mudar para esse caminho.
    image: null,
    // TODO: link de verificação do Coursera ou Credly.
    url: null,
  },
};

const CONTENT = {
  pt: {
    meta: {
      title: "João Gonçalves | Administrador de Sistemas Júnior",
      description:
        "Administrador de sistemas júnior em Viana do Castelo. Linux, Windows Server, Active Directory, redes Cisco e backups. Disponível para estágio a partir de janeiro de 2027.",
    },
    nav: {
      home: "Início",
      about: "Sobre",
      skills: "Competências",
      projects: "Projetos",
      education: "Formação",
      contact: "Contacto",
      menu: "Abrir menu",
      close: "Fechar menu",
      switchLanguage: "Ver em inglês",
      main: "Principal",
      skip: "Saltar para o conteúdo",
    },
    status: { done: "Concluído", current: "Em curso", planned: "Planeado" },
    common: {
      readMore: "Mais sobre mim",
      allProjects: "Todos os projetos",
      allSkills: "Todas as competências",
      allEducation: "Formação completa",
      learning: "a aprender",
      imagePending: "Imagem em breve",
      verify: "Verificar credencial",
      downloadCv: "Descarregar CV",
      copy: "Copiar",
      copied: "Copiado",
      copyError: "Não foi possível copiar",
      goal: "Objetivo",
      scope: "O que inclui",
      deliverables: "O que fica documentado",
      stack: "Tecnologias",
      backHome: "Voltar ao início",
    },
    home: {
      availability: "Disponível para estágio a partir de janeiro de 2027",
      headline: ["Servidores estáveis,", "redes organizadas."],
      subtext:
        "Administrador de sistemas júnior. Linux, Windows Server, Active Directory e redes Cisco, com backups testados e tudo documentado.",
      ctaProjects: "Ver projetos",
      ctaContact: "Contactar",
      photoAlt: "Fotografia de João Gonçalves",
      aboutLead:
        "Estou a formar-me em redes e sistemas no IEFP (nível 5 do QNQ) e já concluí o Google IT Support Professional Certificate. Procuro o primeiro lugar numa equipa de infraestrutura.",
      educationTitle: "Formação e certificações",
      projectsTitle: "Projetos",
      skillsTitle: "Competências",
      contactLead: "Tem uma vaga ou estágio em administração de sistemas?",
    },
    about: {
      title: "Sobre mim",
      intro: "Administrador de sistemas júnior em Viana do Castelo, à procura de estágio a partir de janeiro de 2027.",
      paragraphs: [
        "Estou a fazer o curso de Redes e Sistemas Informáticos no IEFP, de nível 5 do QNQ, e concluí o Google IT Support Professional Certificate. Em paralelo sigo o percurso Network Technician da Cisco Networking Academy, os cursos de Linux para administração de sistemas e o percurso de administrador do Microsoft Learn.",
        "O meu foco é a infraestrutura do dia a dia: contas e permissões no Active Directory, políticas de grupo, servidores Windows e Linux, switching e VLANs, e cópias de segurança que se conseguem restaurar. Monto tudo primeiro no meu laboratório em casa, e cada projeto fica com um diagrama, a configuração e um procedimento escrito.",
        "Quero entrar numa equipa onde possa aprender com administradores mais experientes, assumir tarefas de suporte e manutenção desde o primeiro dia e ganhar responsabilidade à medida que provo trabalho.",
      ],
      principlesTitle: "Como trabalho",
      principles: [
        { title: "Documentar enquanto faço", body: "Cada alteração fica registada com o motivo, os passos e como reverter." },
        { title: "Um backup só conta depois de restaurado", body: "Testo regularmente a recuperação, não apenas a cópia." },
        { title: "Automatizar o que se repete", body: "Tarefas feitas mais de duas vezes passam a script em PowerShell ou Bash." },
        { title: "Menos privilégios por defeito", body: "Contas separadas para administração e acessos dados só quando são precisos." },
      ],
      facts: [
        { label: "Local", value: "Viana do Castelo, Portugal" },
        { label: "Procuro", value: "Sysadmin júnior, suporte de infraestrutura, help desk" },
        { label: "Disponível", value: "Estágio a partir de janeiro de 2027" },
        { label: "Línguas", value: "Português (nativo), inglês" },
      ],
    },
    skills: {
      title: "Competências",
      intro: "O que já uso com confiança e o que estou a aprender agora.",
      groups: [
        {
          id: "systems",
          title: "Sistemas",
          summary: "Servidores Windows e Linux, identidades e permissões.",
          items: [
            { name: "Windows Server" },
            { name: "Active Directory DS" },
            { name: "Política de grupo (GPO)" },
            { name: "DNS e DHCP" },
            { name: "Debian e Ubuntu Server" },
            { name: "Utilizadores, grupos e permissões" },
            { name: "systemd e serviços" },
            { name: "Virtualização (Hyper-V, VirtualBox)" },
            { name: "SSH com chaves e hardening", learning: true },
            { name: "LVM e RAID por software", learning: true },
            { name: "Microsoft Entra ID", learning: true },
          ],
        },
        {
          id: "networking",
          title: "Redes",
          summary: "Do cabo à aplicação, com equipamento Cisco.",
          items: [
            { name: "Modelo OSI e TCP/IP" },
            { name: "Endereçamento IPv4 e subnetting" },
            { name: "VLANs e trunking" },
            { name: "Cisco IOS (configuração base)" },
            { name: "Routing estático" },
            { name: "Diagnóstico com ping, tracert e nslookup" },
            { name: "Cisco Packet Tracer" },
            { name: "IPv6", learning: true },
            { name: "Firewalls (nftables, OPNsense) e VPN", learning: true },
          ],
        },
        {
          id: "automation",
          title: "Automação",
          summary: "Scripts para tarefas repetidas e configurações reproduzíveis.",
          items: [
            { name: "PowerShell" },
            { name: "Bash" },
            { name: "Git" },
            { name: "Agendamento (cron, Task Scheduler)" },
            { name: "Timers do systemd", learning: true },
            { name: "Ansible", learning: true },
          ],
        },
        {
          id: "operations",
          title: "Operações e suporte",
          summary: "Manter os sistemas a funcionar e os utilizadores a trabalhar.",
          items: [
            { name: "Backup e recuperação" },
            { name: "Suporte a utilizadores" },
            { name: "Gestão de tickets" },
            { name: "Documentação técnica" },
            { name: "Instalação de postos de trabalho" },
            { name: "Logs (journalctl, rsyslog)", learning: true },
            { name: "Monitorização de serviços", learning: true },
          ],
        },
      ],
    },
    projects: {
      title: "Projetos",
      intro:
        "Projetos de laboratório que reproduzem o trabalho de uma equipa de infraestrutura. Os planeados vão ser feitos por esta ordem e cada um fica publicado com a documentação.",
      filterLabel: "Filtrar projetos",
      filters: { all: "Todos", linux: "Linux", windows: "Windows", network: "Redes" },
      empty: "Nenhum projeto nesta categoria.",
      items: [
        {
          id: "hybrid-domain",
          title: "Domínio híbrido Windows e Linux",
          status: "done",
          tags: ["windows", "linux"],
          summary:
            "Rede de uma pequena empresa montada de raiz, com Active Directory, servidores Linux e um plano de recuperação testado.",
          goal: "Simular a infraestrutura de uma pequena empresa e conseguir recuperá-la depois de uma falha.",
          scope: [
            "Controlador de domínio Windows Server com DNS e DHCP",
            "Unidades organizacionais, grupos e políticas de grupo por departamento",
            "Servidor Linux com partilhas de ficheiros e servidor web",
            "Cópias de segurança automáticas e teste de restauro completo",
          ],
          deliverables: ["Diagrama da rede", "Plano de recuperação escrito", "Lista de GPO aplicadas"],
          stack: ["Windows Server", "Active Directory", "Debian", "Samba", "Backups"],
        },
        {
          id: "hardened-web-server",
          title: "Servidor web Linux com hardening",
          status: "planned",
          tags: ["linux"],
          summary:
            "Um servidor Debian exposto à internet só com o necessário: SSH apenas com chaves, firewall restritiva, atualizações de segurança automáticas e Nginx com HTTPS.",
          goal: "Pôr um serviço online com uma superfície de ataque pequena, conhecida e documentada.",
          scope: [
            "SSH só com chaves, sem login de root e com utilizador de administração separado",
            "Firewall nftables a negar tudo por defeito, com fail2ban no SSH",
            "Atualizações de segurança automáticas com unattended-upgrades",
            "Nginx com certificado Let's Encrypt e cabeçalhos de segurança",
            "Auditoria com Lynis antes e depois, para medir a diferença",
          ],
          deliverables: ["Checklist de hardening com o motivo de cada alteração", "Relatório Lynis antes e depois", "Configurações do Nginx e da firewall"],
          stack: ["Debian", "OpenSSH", "nftables", "fail2ban", "Nginx", "Let's Encrypt", "Lynis"],
        },
        {
          id: "bash-toolkit",
          title: "Kit de manutenção em Bash",
          status: "planned",
          tags: ["linux"],
          summary:
            "Scripts Bash testados para as verificações diárias de um servidor, corridos por timers do systemd e com relatório por email.",
          goal: "Trocar a lista de verificação manual da manhã por scripts que correm sozinhos e só avisam quando algo está mal.",
          scope: [
            "Relatório de estado: disco, memória, carga, serviços falhados e atualizações pendentes",
            "Criação de utilizadores a partir de CSV, com palavra-passe temporária e mudança obrigatória",
            "Backup de /etc e das pastas pessoais com rsync e rotação",
            "Timers do systemd em vez de cron, com registos no journal",
            "Scripts validados com ShellCheck, com set -euo pipefail e modo --dry-run",
          ],
          deliverables: ["Repositório Git com README", "Ajuda --help em cada script", "Exemplo de relatório"],
          stack: ["Bash", "systemd", "rsync", "ShellCheck", "Git"],
        },
        {
          id: "linux-storage",
          title: "Armazenamento com RAID, LVM e NFS",
          status: "planned",
          tags: ["linux"],
          summary:
            "Servidor de ficheiros com discos em espelho e volumes flexíveis, incluindo uma falha de disco simulada e a sua substituição.",
          goal: "Praticar as tarefas de disco que aparecem em produção: aumentar um volume, trocar um disco avariado e voltar a um snapshot.",
          scope: [
            "RAID 1 com mdadm e LVM por cima",
            "Aumentar volumes e sistemas de ficheiros sem desligar o servidor",
            "Snapshots LVM antes de cada alteração",
            "Partilhas NFS e Samba com permissões por grupo e quotas",
            "Falha de disco simulada e reconstrução do RAID, com o tempo registado",
          ],
          deliverables: ["Esquema dos discos e volumes", "Procedimento de substituição de disco", "Registo do teste de falha"],
          stack: ["Ubuntu Server", "mdadm", "LVM", "XFS", "NFS", "Samba"],
        },
        {
          id: "linux-network-services",
          title: "Serviços de rede em Linux",
          status: "planned",
          tags: ["linux", "network"],
          summary:
            "DNS, DHCP e hora para um pequeno escritório a correr em Linux, com um DNS secundário para redundância.",
          goal: "Perceber os serviços de rede base sem interface gráfica e comparar com a mesma montagem em Windows Server.",
          scope: [
            "BIND9 com zona interna, servidor primário e secundário com transferência de zona",
            "Kea DHCP com reservas e atualização automática do DNS",
            "chrony como servidor NTP da rede",
            "Diagnóstico com dig e journalctl",
            "Teste de falha: desligar o DNS primário e confirmar que a rede continua a resolver",
          ],
          deliverables: ["Ficheiros de zona e configurações", "Tabela de endereços e reservas", "Comparação com DNS e DHCP do Windows Server"],
          stack: ["Debian", "BIND9", "Kea DHCP", "chrony", "dig"],
        },
        {
          id: "central-logging",
          title: "Registos centralizados e auditoria",
          status: "planned",
          tags: ["linux"],
          summary:
            "Todos os servidores enviam os registos para um só sítio, com retenção definida e alertas para logins falhados e uso de sudo.",
          goal: "Responder a \"quem fez o quê, e quando\" em qualquer servidor sem entrar em cada um.",
          scope: [
            "rsyslog a enviar registos por TLS para um servidor central",
            "journald persistente com limites de tamanho",
            "Política de retenção com logrotate",
            "Regras auditd para sudo e alterações em /etc/passwd e /etc/sudoers",
            "Relatório diário de logins SSH falhados e comandos sudo",
          ],
          deliverables: ["Diagrama da arquitetura", "Política de retenção", "Regras auditd comentadas", "Exemplo de relatório diário"],
          stack: ["Debian", "rsyslog", "journald", "logrotate", "auditd"],
        },
        {
          id: "network-segmentation",
          title: "Rede segmentada com VLANs e firewall",
          status: "planned",
          tags: ["network"],
          summary:
            "Separar servidores, utilizadores, convidados e gestão em VLANs, com regras de firewall entre elas e acesso remoto por VPN.",
          goal: "Desenhar, configurar e documentar uma rede pequena com segurança básica.",
          scope: [
            "Plano de endereçamento e VLANs desenhado antes de configurar",
            "Switch Cisco com VLANs, trunk e portas de acesso",
            "Firewall OPNsense com regras entre redes",
            "Acesso remoto com WireGuard",
            "Primeiro em Packet Tracer, depois em máquinas virtuais",
          ],
          deliverables: ["Diagrama de rede", "Tabela de endereçamento", "Configurações exportadas", "Regras de firewall comentadas"],
          stack: ["Cisco IOS", "Packet Tracer", "OPNsense", "WireGuard"],
        },
        {
          id: "backup-restore",
          title: "Backups 3-2-1 com restauro testado",
          status: "planned",
          tags: ["linux", "windows"],
          summary:
            "Estratégia de cópias de segurança para servidores Windows e Linux, com uma cópia fora do local e testes de restauro agendados.",
          goal: "Ter um processo de backup em que o restauro está provado e medido, não apenas assumido.",
          scope: [
            "Política 3-2-1: três cópias, dois suportes, uma fora do local",
            "Backups de máquinas virtuais e de ficheiros",
            "Encriptação e retenção definidas",
            "Teste mensal de restauro com o tempo registado",
          ],
          deliverables: ["Política de backup", "Procedimento de restauro passo a passo", "Registo dos testes"],
          stack: ["Proxmox Backup Server", "restic", "Windows Server Backup", "Bash"],
        },
        {
          id: "monitoring",
          title: "Monitorização e alertas",
          status: "planned",
          tags: ["linux", "windows", "network"],
          summary:
            "Painel com o estado de servidores, serviços e rede, e alertas quando algo falha ou um disco está a encher.",
          goal: "Saber que um serviço caiu antes de um utilizador reclamar.",
          scope: [
            "Agentes em servidores Windows e Linux",
            "SNMP no switch",
            "Alertas por email para disco, memória e serviços parados",
            "Painel com o estado geral",
          ],
          deliverables: ["Lista do que é monitorizado e porquê", "Limites de alerta", "Capturas do painel"],
          stack: ["Zabbix", "SNMP", "Linux", "Windows Server"],
        },
        {
          id: "automation",
          title: "Automação de contas e servidores",
          status: "planned",
          tags: ["windows", "linux"],
          summary:
            "Criar e desativar contas de colaboradores no Active Directory a partir de um ficheiro, e preparar servidores Linux sempre da mesma forma.",
          goal: "Reduzir tarefas manuais repetidas e os erros que vêm com elas.",
          scope: [
            "Script PowerShell de entrada e saída de colaboradores a partir de CSV",
            "Registo de todas as alterações feitas pelo script",
            "Playbooks Ansible para atualizações, utilizadores e SSH",
            "Código num repositório Git com instruções de uso",
          ],
          deliverables: ["Repositório com scripts e README", "Exemplo de ficheiro de entrada", "Registo de execução"],
          stack: ["PowerShell", "Active Directory", "Ansible", "Git"],
        },
      ],
    },
    education: {
      title: "Formação",
      intro: "Certificações, cursos em curso e formação, com foco em sistemas, redes e suporte.",
      certificationsTitle: "Certificações",
      certifications: [
        {
          id: "google-it-support",
          title: "Google IT Support Professional Certificate",
          issuer: "Google, via Coursera",
          status: "done",
          detail:
            "Cinco cursos: fundamentos de suporte técnico, redes, sistemas operativos, administração de sistemas e serviços de infraestrutura, e segurança informática.",
          imageAlt: "Diploma do Google IT Support Professional Certificate",
        },
      ],
      learningTitle: "Em curso",
      learningItems: [
        {
          id: "cisco-network-technician",
          title: "Network Technician Career Path (CCNA)",
          issuer: "Cisco Networking Academy",
          status: "current",
          detail: "Fundamentos de redes, configuração de equipamentos Cisco, endereçamento e resolução de problemas.",
        },
        {
          id: "cisco-linux",
          title: "Linux para administração de sistemas",
          issuer: "Cisco Networking Academy",
          status: "current",
          detail: "Linha de comandos, utilizadores e permissões, gestão de pacotes e serviços.",
        },
        {
          id: "microsoft-admin",
          title: "Percurso de administrador",
          issuer: "Microsoft Learn",
          status: "current",
          detail: "Administração de ambientes Microsoft e de identidades.",
        },
      ],
      trainingTitle: "Percurso académico",
      training: [
        {
          id: "iefp",
          title: "Redes e Sistemas Informáticos, nível 5 do QNQ",
          issuer: "IEFP, Viana do Castelo",
          status: "current",
          detail: "Administração de servidores Windows e Linux, redes e suporte técnico. Estágio a partir de janeiro de 2027.",
        },
        {
          id: "bsc",
          title: "Licenciatura em Engenharia Informática",
          issuer: "Ensino superior",
          status: "planned",
          detail: "Próximo passo depois do estágio.",
        },
      ],
    },
    contact: {
      title: "Contacto",
      intro:
        "Procuro um estágio ou primeiro emprego em administração de sistemas ou suporte de infraestrutura. A forma mais rápida de me contactar é por email.",
      emailLabel: "Email",
      elsewhere: "Noutros sítios",
      availabilityTitle: "Disponibilidade",
      availability: [
        { label: "Início", value: "Janeiro de 2027" },
        { label: "Local", value: "Viana do Castelo" },
        { label: "Tipo", value: "Estágio ou contrato" },
      ],
    },
    footer: { built: "Feito à mão em HTML, CSS e JavaScript." },
  },

  en: {
    meta: {
      title: "João Gonçalves | Junior Systems Administrator",
      description:
        "Junior systems administrator based in Viana do Castelo, Portugal. Linux, Windows Server, Active Directory, Cisco networking and backups. Available for an internship from January 2027.",
    },
    nav: {
      home: "Home",
      about: "About",
      skills: "Skills",
      projects: "Projects",
      education: "Education",
      contact: "Contact",
      menu: "Open menu",
      close: "Close menu",
      switchLanguage: "Ver em português",
      main: "Main",
      skip: "Skip to content",
    },
    status: { done: "Completed", current: "In progress", planned: "Planned" },
    common: {
      readMore: "More about me",
      allProjects: "All projects",
      allSkills: "All skills",
      allEducation: "Full education",
      learning: "learning",
      imagePending: "Image coming soon",
      verify: "Verify credential",
      downloadCv: "Download CV",
      copy: "Copy",
      copied: "Copied",
      copyError: "Could not copy",
      goal: "Goal",
      scope: "What it covers",
      deliverables: "What gets documented",
      stack: "Technologies",
      backHome: "Back to home",
    },
    home: {
      availability: "Available for an internship from January 2027",
      headline: ["Stable servers,", "organised networks."],
      subtext:
        "Junior systems administrator. Linux, Windows Server, Active Directory and Cisco networking, with tested backups and everything documented.",
      ctaProjects: "View projects",
      ctaContact: "Contact",
      photoAlt: "Photo of João Gonçalves",
      aboutLead:
        "I am training in networks and systems at IEFP (EQF level 5) and have completed the Google IT Support Professional Certificate. I am looking for my first place in an infrastructure team.",
      educationTitle: "Education and certifications",
      projectsTitle: "Projects",
      skillsTitle: "Skills",
      contactLead: "Hiring for a systems administration role or internship?",
    },
    about: {
      title: "About me",
      intro: "Junior systems administrator in Viana do Castelo, Portugal, looking for an internship from January 2027.",
      paragraphs: [
        "I am taking the Networks and Computer Systems course at IEFP, a level 5 qualification in the Portuguese framework (EQF level 5), and I have completed the Google IT Support Professional Certificate. Alongside it I am following the Cisco Networking Academy Network Technician career path, the Linux courses for systems administration and the Microsoft Learn administrator path.",
        "My focus is everyday infrastructure: accounts and permissions in Active Directory, Group Policy, Windows and Linux servers, switching and VLANs, and backups that can actually be restored. I build everything in my home lab first, and every project ends with a diagram, the configuration and a written procedure.",
        "I want to join a team where I can learn from more experienced administrators, take on support and maintenance tasks from day one and earn more responsibility as I prove my work.",
      ],
      principlesTitle: "How I work",
      principles: [
        { title: "Document while doing", body: "Every change is recorded with the reason, the steps and how to roll it back." },
        { title: "A backup only counts once restored", body: "I test recovery regularly, not just the copy." },
        { title: "Automate what repeats", body: "Anything done more than twice becomes a PowerShell or Bash script." },
        { title: "Least privilege by default", body: "Separate admin accounts, and access granted only when it is needed." },
      ],
      facts: [
        { label: "Location", value: "Viana do Castelo, Portugal" },
        { label: "Looking for", value: "Junior sysadmin, infrastructure support, help desk" },
        { label: "Available", value: "Internship from January 2027" },
        { label: "Languages", value: "Portuguese (native), English" },
      ],
    },
    skills: {
      title: "Skills",
      intro: "What I already use with confidence, and what I am learning right now.",
      groups: [
        {
          id: "systems",
          title: "Systems",
          summary: "Windows and Linux servers, identities and permissions.",
          items: [
            { name: "Windows Server" },
            { name: "Active Directory DS" },
            { name: "Group Policy (GPO)" },
            { name: "DNS and DHCP" },
            { name: "Debian and Ubuntu Server" },
            { name: "Users, groups and permissions" },
            { name: "systemd and services" },
            { name: "Virtualisation (Hyper-V, VirtualBox)" },
            { name: "Key-based SSH and hardening", learning: true },
            { name: "LVM and software RAID", learning: true },
            { name: "Microsoft Entra ID", learning: true },
          ],
        },
        {
          id: "networking",
          title: "Networking",
          summary: "From the cable to the application, on Cisco equipment.",
          items: [
            { name: "OSI and TCP/IP models" },
            { name: "IPv4 addressing and subnetting" },
            { name: "VLANs and trunking" },
            { name: "Cisco IOS (base configuration)" },
            { name: "Static routing" },
            { name: "Troubleshooting with ping, tracert and nslookup" },
            { name: "Cisco Packet Tracer" },
            { name: "IPv6", learning: true },
            { name: "Firewalls (nftables, OPNsense) and VPN", learning: true },
          ],
        },
        {
          id: "automation",
          title: "Automation",
          summary: "Scripts for repeated tasks and reproducible configuration.",
          items: [
            { name: "PowerShell" },
            { name: "Bash" },
            { name: "Git" },
            { name: "Scheduling (cron, Task Scheduler)" },
            { name: "systemd timers", learning: true },
            { name: "Ansible", learning: true },
          ],
        },
        {
          id: "operations",
          title: "Operations and support",
          summary: "Keeping systems running and users working.",
          items: [
            { name: "Backup and recovery" },
            { name: "User support" },
            { name: "Ticket handling" },
            { name: "Technical documentation" },
            { name: "Workstation setup" },
            { name: "Logs (journalctl, rsyslog)", learning: true },
            { name: "Service monitoring", learning: true },
          ],
        },
      ],
    },
    projects: {
      title: "Projects",
      intro:
        "Lab projects that reproduce the work of an infrastructure team. The planned ones will be built in this order, and each is published with its documentation.",
      filterLabel: "Filter projects",
      filters: { all: "All", linux: "Linux", windows: "Windows", network: "Networking" },
      empty: "No projects in this category.",
      items: [
        {
          id: "hybrid-domain",
          title: "Hybrid Windows and Linux domain",
          status: "done",
          tags: ["windows", "linux"],
          summary:
            "A small-business network built from scratch, with Active Directory, Linux servers and a tested recovery plan.",
          goal: "Simulate a small company's infrastructure and be able to recover it after a failure.",
          scope: [
            "Windows Server domain controller with DNS and DHCP",
            "Organisational units, groups and Group Policy per department",
            "Linux server with file shares and a web server",
            "Automated backups and a full restore test",
          ],
          deliverables: ["Network diagram", "Written recovery plan", "List of applied GPOs"],
          stack: ["Windows Server", "Active Directory", "Debian", "Samba", "Backups"],
        },
        {
          id: "hardened-web-server",
          title: "Hardened Linux web server",
          status: "planned",
          tags: ["linux"],
          summary:
            "A Debian server exposed to the internet with only what it needs: key-only SSH, a restrictive firewall, automatic security updates and Nginx with HTTPS.",
          goal: "Put a service online with an attack surface that is small, known and documented.",
          scope: [
            "Key-only SSH, no root login and a separate admin user",
            "nftables firewall denying everything by default, with fail2ban on SSH",
            "Automatic security updates with unattended-upgrades",
            "Nginx with a Let's Encrypt certificate and security headers",
            "Lynis audit before and after, to measure the difference",
          ],
          deliverables: ["Hardening checklist with the reason for each change", "Lynis report before and after", "Nginx and firewall configuration"],
          stack: ["Debian", "OpenSSH", "nftables", "fail2ban", "Nginx", "Let's Encrypt", "Lynis"],
        },
        {
          id: "bash-toolkit",
          title: "Bash maintenance toolkit",
          status: "planned",
          tags: ["linux"],
          summary:
            "Tested Bash scripts for a server's daily checks, run by systemd timers and reporting by email.",
          goal: "Replace the manual morning checklist with scripts that run on their own and only speak up when something is wrong.",
          scope: [
            "Health report: disk, memory, load, failed services and pending updates",
            "User creation from CSV, with a temporary password that must be changed",
            "rsync backup of /etc and home directories, with rotation",
            "systemd timers instead of cron, with logs in the journal",
            "Scripts checked with ShellCheck, using set -euo pipefail and a --dry-run mode",
          ],
          deliverables: ["Git repository with README", "--help output in every script", "Sample report"],
          stack: ["Bash", "systemd", "rsync", "ShellCheck", "Git"],
        },
        {
          id: "linux-storage",
          title: "Storage with RAID, LVM and NFS",
          status: "planned",
          tags: ["linux"],
          summary:
            "A file server with mirrored disks and flexible volumes, including a simulated disk failure and replacement.",
          goal: "Practise the disk tasks that come up in production: growing a volume, replacing a failed disk and rolling back to a snapshot.",
          scope: [
            "RAID 1 with mdadm, with LVM on top",
            "Growing volumes and filesystems without taking the server down",
            "LVM snapshots before every change",
            "NFS and Samba shares with per-group permissions and quotas",
            "Simulated disk failure and RAID rebuild, with the time recorded",
          ],
          deliverables: ["Disk and volume layout", "Disk replacement procedure", "Failure test log"],
          stack: ["Ubuntu Server", "mdadm", "LVM", "XFS", "NFS", "Samba"],
        },
        {
          id: "linux-network-services",
          title: "Network services on Linux",
          status: "planned",
          tags: ["linux", "network"],
          summary:
            "DNS, DHCP and time for a small office running on Linux, with a secondary DNS server for redundancy.",
          goal: "Understand core network services without a GUI and compare them with the same setup on Windows Server.",
          scope: [
            "BIND9 with an internal zone, primary and secondary servers with zone transfer",
            "Kea DHCP with reservations and automatic DNS updates",
            "chrony as the network's NTP server",
            "Troubleshooting with dig and journalctl",
            "Failure test: switch off the primary DNS and confirm the network still resolves",
          ],
          deliverables: ["Zone files and configuration", "Address and reservation table", "Comparison with Windows Server DNS and DHCP"],
          stack: ["Debian", "BIND9", "Kea DHCP", "chrony", "dig"],
        },
        {
          id: "central-logging",
          title: "Centralised logging and auditing",
          status: "planned",
          tags: ["linux"],
          summary:
            "Every server ships its logs to one place, with a defined retention and alerts for failed logins and sudo use.",
          goal: "Answer \"who did what, and when\" on any server without logging into each one.",
          scope: [
            "rsyslog forwarding logs over TLS to a central server",
            "Persistent journald with size limits",
            "Retention policy with logrotate",
            "auditd rules for sudo and changes to /etc/passwd and /etc/sudoers",
            "Daily report of failed SSH logins and sudo commands",
          ],
          deliverables: ["Architecture diagram", "Retention policy", "Commented auditd rules", "Sample daily report"],
          stack: ["Debian", "rsyslog", "journald", "logrotate", "auditd"],
        },
        {
          id: "network-segmentation",
          title: "Segmented network with VLANs and firewall",
          status: "planned",
          tags: ["network"],
          summary:
            "Split servers, users, guests and management into VLANs, with firewall rules between them and remote access over VPN.",
          goal: "Design, configure and document a small network with basic security.",
          scope: [
            "Addressing and VLAN plan designed before configuring",
            "Cisco switch with VLANs, trunk and access ports",
            "OPNsense firewall with rules between networks",
            "Remote access with WireGuard",
            "Built in Packet Tracer first, then on virtual machines",
          ],
          deliverables: ["Network diagram", "Addressing table", "Exported configurations", "Commented firewall rules"],
          stack: ["Cisco IOS", "Packet Tracer", "OPNsense", "WireGuard"],
        },
        {
          id: "backup-restore",
          title: "3-2-1 backups with tested restores",
          status: "planned",
          tags: ["linux", "windows"],
          summary:
            "A backup strategy for Windows and Linux servers, with an off-site copy and scheduled restore tests.",
          goal: "Have a backup process where restoring is proven and measured, not assumed.",
          scope: [
            "3-2-1 policy: three copies, two media, one off-site",
            "Virtual machine and file backups",
            "Defined encryption and retention",
            "Monthly restore test with the time recorded",
          ],
          deliverables: ["Backup policy", "Step-by-step restore procedure", "Test log"],
          stack: ["Proxmox Backup Server", "restic", "Windows Server Backup", "Bash"],
        },
        {
          id: "monitoring",
          title: "Monitoring and alerting",
          status: "planned",
          tags: ["linux", "windows", "network"],
          summary:
            "A dashboard showing the state of servers, services and network, with alerts when something fails or a disk is filling up.",
          goal: "Know a service is down before a user reports it.",
          scope: [
            "Agents on Windows and Linux servers",
            "SNMP on the switch",
            "Email alerts for disk, memory and stopped services",
            "Overview dashboard",
          ],
          deliverables: ["What is monitored and why", "Alert thresholds", "Dashboard screenshots"],
          stack: ["Zabbix", "SNMP", "Linux", "Windows Server"],
        },
        {
          id: "automation",
          title: "Account and server automation",
          status: "planned",
          tags: ["windows", "linux"],
          summary:
            "Create and disable staff accounts in Active Directory from a file, and set up Linux servers the same way every time.",
          goal: "Cut repeated manual tasks and the mistakes that come with them.",
          scope: [
            "PowerShell onboarding and offboarding script driven by CSV",
            "Log of every change the script makes",
            "Ansible playbooks for updates, users and SSH",
            "Code in a Git repository with usage instructions",
          ],
          deliverables: ["Repository with scripts and README", "Sample input file", "Run log"],
          stack: ["PowerShell", "Active Directory", "Ansible", "Git"],
        },
      ],
    },
    education: {
      title: "Education",
      intro: "Certifications, courses in progress and formal training, focused on systems, networking and support.",
      certificationsTitle: "Certifications",
      certifications: [
        {
          id: "google-it-support",
          title: "Google IT Support Professional Certificate",
          issuer: "Google, via Coursera",
          status: "done",
          detail:
            "Five courses: technical support fundamentals, computer networking, operating systems, system administration and IT infrastructure services, and IT security.",
          imageAlt: "Google IT Support Professional Certificate diploma",
        },
      ],
      learningTitle: "In progress",
      learningItems: [
        {
          id: "cisco-network-technician",
          title: "Network Technician Career Path (CCNA)",
          issuer: "Cisco Networking Academy",
          status: "current",
          detail: "Networking fundamentals, Cisco device configuration, addressing and troubleshooting.",
        },
        {
          id: "cisco-linux",
          title: "Linux for systems administration",
          issuer: "Cisco Networking Academy",
          status: "current",
          detail: "Command line, users and permissions, package and service management.",
        },
        {
          id: "microsoft-admin",
          title: "Administrator career path",
          issuer: "Microsoft Learn",
          status: "current",
          detail: "Administration of Microsoft environments and identities.",
        },
      ],
      trainingTitle: "Training",
      training: [
        {
          id: "iefp",
          title: "Networks and Computer Systems, EQF level 5",
          issuer: "IEFP, Viana do Castelo",
          status: "current",
          detail: "Windows and Linux server administration, networking and technical support. Internship from January 2027.",
        },
        {
          id: "bsc",
          title: "BSc in Computer Science",
          issuer: "Higher education",
          status: "planned",
          detail: "Next step after the internship.",
        },
      ],
    },
    contact: {
      title: "Contact",
      intro:
        "I am looking for an internship or first job in systems administration or infrastructure support. Email is the fastest way to reach me.",
      emailLabel: "Email",
      elsewhere: "Elsewhere",
      availabilityTitle: "Availability",
      availability: [
        { label: "Start", value: "January 2027" },
        { label: "Location", value: "Viana do Castelo" },
        { label: "Type", value: "Internship or contract" },
      ],
    },
    footer: { built: "Hand-built with HTML, CSS and JavaScript." },
  },
};
