import type { Dictionary } from "./types";

export const en: Dictionary = {
  meta: {
    title: "João Gonçalves | Junior Systems Administrator",
    description:
      "Junior systems administrator based in Viana do Castelo, Portugal. Windows Server, Active Directory, Linux, Cisco networking and backups. Available for an internship from January 2027.",
  },
  nav: {
    home: "Home",
    about: "About",
    skills: "Skills",
    projects: "Projects",
    education: "Education",
    contact: "Contact",
    menu: "Open menu",
    close: "Close menu",
    switchLanguage: "Ver em português",
    main: "Main",
  },
  status: { done: "Completed", current: "In progress", planned: "Planned" },
  common: {
    readMore: "More about me",
    allProjects: "All projects",
    allSkills: "All skills",
    allEducation: "Full education",
    learning: "learning",
    imagePending: "Image coming soon",
    verify: "Verify credential",
    downloadCv: "Download CV",
    copy: "Copy",
    copied: "Copied",
    copyError: "Could not copy",
    goal: "Goal",
    scope: "What it covers",
    deliverables: "What gets documented",
    stack: "Technologies",
    backHome: "Back to home",
  },
  home: {
    availability: "Available for an internship from January 2027",
    headline: ["Stable servers,", "organised networks."],
    subtext:
      "Junior systems administrator. Windows Server, Active Directory, Linux and Cisco networking, with tested backups and everything documented.",
    ctaProjects: "View projects",
    ctaContact: "Contact",
    photoAlt: "Photo of João Gonçalves",
    aboutLead:
      "I am training in networks and systems at IEFP (EQF level 5) and have completed the Google IT Support Professional Certificate. I am looking for my first place in an infrastructure team.",
    educationTitle: "Education and certifications",
    projectsTitle: "Projects",
    skillsTitle: "Skills",
    contactLead: "Hiring for a systems administration role or internship?",
  },
  about: {
    title: "About me",
    intro: "Junior systems administrator in Viana do Castelo, Portugal, looking for an internship from January 2027.",
    paragraphs: [
      "I am taking the Networks and Computer Systems course at IEFP, a level 5 qualification in the Portuguese framework (EQF level 5), and I have completed the Google IT Support Professional Certificate. Alongside it I am following the Cisco Networking Academy Network Technician career path, the Linux courses for systems administration and the Microsoft Learn administrator path.",
      "My focus is everyday infrastructure: accounts and permissions in Active Directory, Group Policy, Windows and Linux servers, switching and VLANs, and backups that can actually be restored. I build everything in my home lab first, and every project ends with a diagram, the configuration and a written procedure.",
      "I want to join a team where I can learn from more experienced administrators, take on support and maintenance tasks from day one and earn more responsibility as I prove my work.",
    ],
    principlesTitle: "How I work",
    principles: [
      {
        title: "Document while doing",
        body: "Every change is recorded with the reason, the steps and how to roll it back.",
      },
      {
        title: "A backup only counts once restored",
        body: "I test recovery regularly, not just the copy.",
      },
      {
        title: "Automate what repeats",
        body: "Anything done more than twice becomes a PowerShell or Bash script.",
      },
      {
        title: "Least privilege by default",
        body: "Separate admin accounts, and access granted only when it is needed.",
      },
    ],
    facts: [
      { label: "Location", value: "Viana do Castelo, Portugal" },
      { label: "Looking for", value: "Junior sysadmin, infrastructure support, help desk" },
      { label: "Available", value: "Internship from January 2027" },
      { label: "Languages", value: "Portuguese (native), English" },
    ],
  },
  skills: {
    title: "Skills",
    intro: "What I already use with confidence, and what I am learning right now.",
    groups: [
      {
        id: "systems",
        title: "Systems",
        summary: "Windows and Linux servers, identities and permissions.",
        items: [
          { name: "Windows Server" },
          { name: "Active Directory DS" },
          { name: "Group Policy (GPO)" },
          { name: "DNS and DHCP" },
          { name: "Debian and Ubuntu Server" },
          { name: "Users, groups and permissions" },
          { name: "systemd and services" },
          { name: "Virtualisation (Hyper-V, VirtualBox)" },
          { name: "Microsoft Entra ID", learning: true },
        ],
      },
      {
        id: "networking",
        title: "Networking",
        summary: "From the cable to the application, on Cisco equipment.",
        items: [
          { name: "OSI and TCP/IP models" },
          { name: "IPv4 addressing and subnetting" },
          { name: "VLANs and trunking" },
          { name: "Cisco IOS (base configuration)" },
          { name: "Static routing" },
          { name: "Troubleshooting with ping, tracert and nslookup" },
          { name: "Cisco Packet Tracer" },
          { name: "IPv6", learning: true },
          { name: "Firewalls and VPN", learning: true },
        ],
      },
      {
        id: "automation",
        title: "Automation",
        summary: "Scripts for repeated tasks and reproducible configuration.",
        items: [
          { name: "PowerShell" },
          { name: "Bash" },
          { name: "Git" },
          { name: "Scheduling (cron, Task Scheduler)" },
          { name: "Ansible", learning: true },
        ],
      },
      {
        id: "operations",
        title: "Operations and support",
        summary: "Keeping systems running and users working.",
        items: [
          { name: "Backup and recovery" },
          { name: "User support" },
          { name: "Ticket handling" },
          { name: "Technical documentation" },
          { name: "Workstation setup" },
          { name: "Service monitoring", learning: true },
        ],
      },
    ],
  },
  projects: {
    title: "Projects",
    intro:
      "Lab projects that reproduce the work of an infrastructure team. The planned ones will be built in this order, and each is published with its documentation.",
    items: [
      {
        id: "hybrid-domain",
        title: "Hybrid Windows and Linux domain",
        status: "done",
        summary:
          "A small-business network built from scratch, with Active Directory, Linux servers and a tested recovery plan.",
        goal: "Simulate a small company's infrastructure and be able to recover it after a failure.",
        scope: [
          "Windows Server domain controller with DNS and DHCP",
          "Organisational units, groups and Group Policy per department",
          "Linux server with file shares and a web server",
          "Automated backups and a full restore test",
        ],
        deliverables: ["Network diagram", "Written recovery plan", "List of applied GPOs"],
        stack: ["Windows Server", "Active Directory", "Debian", "Samba", "Backups"],
      },
      {
        id: "network-segmentation",
        title: "Segmented network with VLANs and firewall",
        status: "planned",
        summary:
          "Split servers, users, guests and management into VLANs, with firewall rules between them and remote access over VPN.",
        goal: "Design, configure and document a small network with basic security.",
        scope: [
          "Addressing and VLAN plan designed before configuring",
          "Cisco switch with VLANs, trunk and access ports",
          "OPNsense firewall with rules between networks",
          "Remote access with WireGuard",
          "Built in Packet Tracer first, then on virtual machines",
        ],
        deliverables: ["Network diagram", "Addressing table", "Exported configurations", "Commented firewall rules"],
        stack: ["Cisco IOS", "Packet Tracer", "OPNsense", "WireGuard"],
      },
      {
        id: "backup-restore",
        title: "3-2-1 backups with tested restores",
        status: "planned",
        summary:
          "A backup strategy for Windows and Linux servers, with an off-site copy and scheduled restore tests.",
        goal: "Have a backup process where restoring is proven and measured, not assumed.",
        scope: [
          "3-2-1 policy: three copies, two media, one off-site",
          "Virtual machine and file backups",
          "Defined encryption and retention",
          "Monthly restore test with the time recorded",
        ],
        deliverables: ["Backup policy", "Step-by-step restore procedure", "Test log"],
        stack: ["Proxmox Backup Server", "restic", "Windows Server Backup", "Bash"],
      },
      {
        id: "monitoring",
        title: "Monitoring and alerting",
        status: "planned",
        summary:
          "A dashboard showing the state of servers, services and network, with alerts when something fails or a disk is filling up.",
        goal: "Know a service is down before a user reports it.",
        scope: [
          "Agents on Windows and Linux servers",
          "SNMP on the switch",
          "Email alerts for disk, memory and stopped services",
          "Overview dashboard",
        ],
        deliverables: ["What is monitored and why", "Alert thresholds", "Dashboard screenshots"],
        stack: ["Zabbix", "SNMP", "Linux", "Windows Server"],
      },
      {
        id: "automation",
        title: "Account and server automation",
        status: "planned",
        summary:
          "Create and disable staff accounts in Active Directory from a file, and set up Linux servers the same way every time.",
        goal: "Cut repeated manual tasks and the mistakes that come with them.",
        scope: [
          "PowerShell onboarding and offboarding script driven by CSV",
          "Log of every change the script makes",
          "Ansible playbooks for updates, users and SSH",
          "Code in a Git repository with usage instructions",
        ],
        deliverables: ["Repository with scripts and README", "Sample input file", "Run log"],
        stack: ["PowerShell", "Active Directory", "Ansible", "Git"],
      },
    ],
  },
  education: {
    title: "Education",
    intro: "Certifications, courses in progress and formal training, focused on systems, networking and support.",
    certificationsTitle: "Certifications",
    certifications: [
      {
        id: "google-it-support",
        title: "Google IT Support Professional Certificate",
        issuer: "Google, via Coursera",
        status: "done",
        detail:
          "Five courses: technical support fundamentals, computer networking, operating systems, system administration and IT infrastructure services, and IT security.",
        imageAlt: "Google IT Support Professional Certificate diploma",
      },
    ],
    learningTitle: "In progress",
    learningItems: [
      {
        id: "cisco-network-technician",
        title: "Network Technician Career Path (CCNA)",
        issuer: "Cisco Networking Academy",
        status: "current",
        detail: "Networking fundamentals, Cisco device configuration, addressing and troubleshooting.",
      },
      {
        id: "cisco-linux",
        title: "Linux for systems administration",
        issuer: "Cisco Networking Academy",
        status: "current",
        detail: "Command line, users and permissions, package and service management.",
      },
      {
        id: "microsoft-admin",
        title: "Administrator career path",
        issuer: "Microsoft Learn",
        status: "current",
        detail: "Administration of Microsoft environments and identities.",
      },
    ],
    trainingTitle: "Training",
    training: [
      {
        id: "iefp",
        title: "Networks and Computer Systems, EQF level 5",
        issuer: "IEFP, Viana do Castelo",
        status: "current",
        detail: "Windows and Linux server administration, networking and technical support. Internship from January 2027.",
      },
      {
        id: "bsc",
        title: "BSc in Computer Science",
        issuer: "Higher education",
        status: "planned",
        detail: "Next step after the internship.",
      },
    ],
  },
  contact: {
    title: "Contact",
    intro:
      "I am looking for an internship or first job in systems administration or infrastructure support. Email is the fastest way to reach me.",
    emailLabel: "Email",
    elsewhere: "Elsewhere",
    availabilityTitle: "Availability",
    availability: [
      { label: "Start", value: "January 2027" },
      { label: "Location", value: "Viana do Castelo" },
      { label: "Type", value: "Internship or contract" },
    ],
  },
  footer: { built: "Built with Next.js." },
};
