import type { Dictionary } from "./types";

export const pt: Dictionary = {
  meta: {
    title: "João Gonçalves | Administrador de Sistemas Júnior",
    description:
      "Administrador de sistemas júnior em Viana do Castelo. Windows Server, Active Directory, Linux, redes Cisco e backups. Disponível para estágio a partir de janeiro de 2027.",
  },
  nav: {
    home: "Início",
    about: "Sobre",
    skills: "Competências",
    projects: "Projetos",
    education: "Formação",
    contact: "Contacto",
    menu: "Abrir menu",
    close: "Fechar menu",
    switchLanguage: "Ver em inglês",
    main: "Principal",
  },
  status: { done: "Concluído", current: "Em curso", planned: "Planeado" },
  common: {
    readMore: "Mais sobre mim",
    allProjects: "Todos os projetos",
    allSkills: "Todas as competências",
    allEducation: "Formação completa",
    learning: "a aprender",
    imagePending: "Imagem em breve",
    verify: "Verificar credencial",
    downloadCv: "Descarregar CV",
    copy: "Copiar",
    copied: "Copiado",
    copyError: "Não foi possível copiar",
    goal: "Objetivo",
    scope: "O que inclui",
    deliverables: "O que fica documentado",
    stack: "Tecnologias",
    backHome: "Voltar ao início",
  },
  home: {
    availability: "Disponível para estágio a partir de janeiro de 2027",
    headline: ["Servidores estáveis,", "redes organizadas."],
    subtext:
      "Administrador de sistemas júnior. Windows Server, Active Directory, Linux e redes Cisco, com backups testados e tudo documentado.",
    ctaProjects: "Ver projetos",
    ctaContact: "Contactar",
    photoAlt: "Fotografia de João Gonçalves",
    aboutLead:
      "Estou a formar-me em redes e sistemas no IEFP (nível 5 do QNQ) e já concluí o Google IT Support Professional Certificate. Procuro o primeiro lugar numa equipa de infraestrutura.",
    educationTitle: "Formação e certificações",
    projectsTitle: "Projetos",
    skillsTitle: "Competências",
    contactLead: "Tem uma vaga ou estágio em administração de sistemas?",
  },
  about: {
    title: "Sobre mim",
    intro: "Administrador de sistemas júnior em Viana do Castelo, à procura de estágio a partir de janeiro de 2027.",
    paragraphs: [
      "Estou a fazer o curso de Redes e Sistemas Informáticos no IEFP, de nível 5 do QNQ, e concluí o Google IT Support Professional Certificate. Em paralelo sigo o percurso Network Technician da Cisco Networking Academy, os cursos de Linux para administração de sistemas e o percurso de administrador do Microsoft Learn.",
      "O meu foco é a infraestrutura do dia a dia: contas e permissões no Active Directory, políticas de grupo, servidores Windows e Linux, switching e VLANs, e cópias de segurança que se conseguem restaurar. Monto tudo primeiro no meu laboratório em casa, e cada projeto fica com um diagrama, a configuração e um procedimento escrito.",
      "Quero entrar numa equipa onde possa aprender com administradores mais experientes, assumir tarefas de suporte e manutenção desde o primeiro dia e ganhar responsabilidade à medida que provo trabalho.",
    ],
    principlesTitle: "Como trabalho",
    principles: [
      {
        title: "Documentar enquanto faço",
        body: "Cada alteração fica registada com o motivo, os passos e como reverter.",
      },
      {
        title: "Um backup só conta depois de restaurado",
        body: "Testo regularmente a recuperação, não apenas a cópia.",
      },
      {
        title: "Automatizar o que se repete",
        body: "Tarefas feitas mais de duas vezes passam a script em PowerShell ou Bash.",
      },
      {
        title: "Menos privilégios por defeito",
        body: "Contas separadas para administração e acessos dados só quando são precisos.",
      },
    ],
    facts: [
      { label: "Local", value: "Viana do Castelo, Portugal" },
      { label: "Procuro", value: "Sysadmin júnior, suporte de infraestrutura, help desk" },
      { label: "Disponível", value: "Estágio a partir de janeiro de 2027" },
      { label: "Línguas", value: "Português (nativo), inglês" },
    ],
  },
  skills: {
    title: "Competências",
    intro: "O que já uso com confiança e o que estou a aprender agora.",
    groups: [
      {
        id: "systems",
        title: "Sistemas",
        summary: "Servidores Windows e Linux, identidades e permissões.",
        items: [
          { name: "Windows Server" },
          { name: "Active Directory DS" },
          { name: "Política de grupo (GPO)" },
          { name: "DNS e DHCP" },
          { name: "Debian e Ubuntu Server" },
          { name: "Utilizadores, grupos e permissões" },
          { name: "systemd e serviços" },
          { name: "Virtualização (Hyper-V, VirtualBox)" },
          { name: "Microsoft Entra ID", learning: true },
        ],
      },
      {
        id: "networking",
        title: "Redes",
        summary: "Do cabo à aplicação, com equipamento Cisco.",
        items: [
          { name: "Modelo OSI e TCP/IP" },
          { name: "Endereçamento IPv4 e subnetting" },
          { name: "VLANs e trunking" },
          { name: "Cisco IOS (configuração base)" },
          { name: "Routing estático" },
          { name: "Diagnóstico com ping, tracert e nslookup" },
          { name: "Cisco Packet Tracer" },
          { name: "IPv6", learning: true },
          { name: "Firewalls e VPN", learning: true },
        ],
      },
      {
        id: "automation",
        title: "Automação",
        summary: "Scripts para tarefas repetidas e configurações reproduzíveis.",
        items: [
          { name: "PowerShell" },
          { name: "Bash" },
          { name: "Git" },
          { name: "Agendamento (cron, Task Scheduler)" },
          { name: "Ansible", learning: true },
        ],
      },
      {
        id: "operations",
        title: "Operações e suporte",
        summary: "Manter os sistemas a funcionar e os utilizadores a trabalhar.",
        items: [
          { name: "Backup e recuperação" },
          { name: "Suporte a utilizadores" },
          { name: "Gestão de tickets" },
          { name: "Documentação técnica" },
          { name: "Instalação de postos de trabalho" },
          { name: "Monitorização de serviços", learning: true },
        ],
      },
    ],
  },
  projects: {
    title: "Projetos",
    intro:
      "Projetos de laboratório que reproduzem o trabalho de uma equipa de infraestrutura. Os planeados vão ser feitos por esta ordem e cada um fica publicado com a documentação.",
    items: [
      {
        id: "hybrid-domain",
        title: "Domínio híbrido Windows e Linux",
        status: "done",
        summary:
          "Rede de uma pequena empresa montada de raiz, com Active Directory, servidores Linux e um plano de recuperação testado.",
        goal: "Simular a infraestrutura de uma pequena empresa e conseguir recuperá-la depois de uma falha.",
        scope: [
          "Controlador de domínio Windows Server com DNS e DHCP",
          "Unidades organizacionais, grupos e políticas de grupo por departamento",
          "Servidor Linux com partilhas de ficheiros e servidor web",
          "Cópias de segurança automáticas e teste de restauro completo",
        ],
        deliverables: ["Diagrama da rede", "Plano de recuperação escrito", "Lista de GPO aplicadas"],
        stack: ["Windows Server", "Active Directory", "Debian", "Samba", "Backups"],
      },
      {
        id: "network-segmentation",
        title: "Rede segmentada com VLANs e firewall",
        status: "planned",
        summary:
          "Separar servidores, utilizadores, convidados e gestão em VLANs, com regras de firewall entre elas e acesso remoto por VPN.",
        goal: "Desenhar, configurar e documentar uma rede pequena com segurança básica.",
        scope: [
          "Plano de endereçamento e VLANs desenhado antes de configurar",
          "Switch Cisco com VLANs, trunk e portas de acesso",
          "Firewall OPNsense com regras entre redes",
          "Acesso remoto com WireGuard",
          "Primeiro em Packet Tracer, depois em máquinas virtuais",
        ],
        deliverables: ["Diagrama de rede", "Tabela de endereçamento", "Configurações exportadas", "Regras de firewall comentadas"],
        stack: ["Cisco IOS", "Packet Tracer", "OPNsense", "WireGuard"],
      },
      {
        id: "backup-restore",
        title: "Backups 3-2-1 com restauro testado",
        status: "planned",
        summary:
          "Estratégia de cópias de segurança para servidores Windows e Linux, com uma cópia fora do local e testes de restauro agendados.",
        goal: "Ter um processo de backup em que o restauro está provado e medido, não apenas assumido.",
        scope: [
          "Política 3-2-1: três cópias, dois suportes, uma fora do local",
          "Backups de máquinas virtuais e de ficheiros",
          "Encriptação e retenção definidas",
          "Teste mensal de restauro com o tempo registado",
        ],
        deliverables: ["Política de backup", "Procedimento de restauro passo a passo", "Registo dos testes"],
        stack: ["Proxmox Backup Server", "restic", "Windows Server Backup", "Bash"],
      },
      {
        id: "monitoring",
        title: "Monitorização e alertas",
        status: "planned",
        summary:
          "Painel com o estado de servidores, serviços e rede, e alertas quando algo falha ou um disco está a encher.",
        goal: "Saber que um serviço caiu antes de um utilizador reclamar.",
        scope: [
          "Agentes em servidores Windows e Linux",
          "SNMP no switch",
          "Alertas por email para disco, memória e serviços parados",
          "Painel com o estado geral",
        ],
        deliverables: ["Lista do que é monitorizado e porquê", "Limites de alerta", "Capturas do painel"],
        stack: ["Zabbix", "SNMP", "Linux", "Windows Server"],
      },
      {
        id: "automation",
        title: "Automação de contas e servidores",
        status: "planned",
        summary:
          "Criar e desativar contas de colaboradores no Active Directory a partir de um ficheiro, e preparar servidores Linux sempre da mesma forma.",
        goal: "Reduzir tarefas manuais repetidas e os erros que vêm com elas.",
        scope: [
          "Script PowerShell de entrada e saída de colaboradores a partir de CSV",
          "Registo de todas as alterações feitas pelo script",
          "Playbooks Ansible para atualizações, utilizadores e SSH",
          "Código num repositório Git com instruções de uso",
        ],
        deliverables: ["Repositório com scripts e README", "Exemplo de ficheiro de entrada", "Registo de execução"],
        stack: ["PowerShell", "Active Directory", "Ansible", "Git"],
      },
    ],
  },
  education: {
    title: "Formação",
    intro: "Certificações, cursos em curso e formação, com foco em sistemas, redes e suporte.",
    certificationsTitle: "Certificações",
    certifications: [
      {
        id: "google-it-support",
        title: "Google IT Support Professional Certificate",
        issuer: "Google, via Coursera",
        status: "done",
        detail:
          "Cinco cursos: fundamentos de suporte técnico, redes, sistemas operativos, administração de sistemas e serviços de infraestrutura, e segurança informática.",
        imageAlt: "Diploma do Google IT Support Professional Certificate",
      },
    ],
    learningTitle: "Em curso",
    learningItems: [
      {
        id: "cisco-network-technician",
        title: "Network Technician Career Path (CCNA)",
        issuer: "Cisco Networking Academy",
        status: "current",
        detail: "Fundamentos de redes, configuração de equipamentos Cisco, endereçamento e resolução de problemas.",
      },
      {
        id: "cisco-linux",
        title: "Linux para administração de sistemas",
        issuer: "Cisco Networking Academy",
        status: "current",
        detail: "Linha de comandos, utilizadores e permissões, gestão de pacotes e serviços.",
      },
      {
        id: "microsoft-admin",
        title: "Percurso de administrador",
        issuer: "Microsoft Learn",
        status: "current",
        detail: "Administração de ambientes Microsoft e de identidades.",
      },
    ],
    trainingTitle: "Percurso académico",
    training: [
      {
        id: "iefp",
        title: "Redes e Sistemas Informáticos, nível 5 do QNQ",
        issuer: "IEFP, Viana do Castelo",
        status: "current",
        detail: "Administração de servidores Windows e Linux, redes e suporte técnico. Estágio a partir de janeiro de 2027.",
      },
      {
        id: "bsc",
        title: "Licenciatura em Engenharia Informática",
        issuer: "Ensino superior",
        status: "planned",
        detail: "Próximo passo depois do estágio.",
      },
    ],
  },
  contact: {
    title: "Contacto",
    intro:
      "Procuro um estágio ou primeiro emprego em administração de sistemas ou suporte de infraestrutura. A forma mais rápida de me contactar é por email.",
    emailLabel: "Email",
    elsewhere: "Noutros sítios",
    availabilityTitle: "Disponibilidade",
    availability: [
      { label: "Início", value: "Janeiro de 2027" },
      { label: "Local", value: "Viana do Castelo" },
      { label: "Tipo", value: "Estágio ou contrato" },
    ],
  },
  footer: { built: "Feito com Next.js." },
};
